; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{34BEED1C-31A6-4ACA-B457-EDF86DFCF074}
AppName=Kuvempu Kannada Thantramsha 1.5 Test
AppVersion=1.5
;AppVerName=Kuvempu Kannada Thantramsha 1.5 Test 1.5
AppPublisher=MTA
DefaultDirName={pf}\Kuvempu Kannada Thantramsha 1.5 Test
DefaultGroupName=Kuvempu Kannada Thantramsha 1.5 Test
LicenseFile=H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\TestLicense.txt
OutputDir=H:\kannada\ASCII\WINDOWS\KKT v 2.0\Temp Setup
OutputBaseFilename=Kuvempu Test
SetupIconFile=H:\kannada\ASCII\WINDOWS\KKT v 2.0\Kuvempu\res\icon11.ico
Password=mytest123#
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\Kuvempu.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\cauvery.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\Hemavathi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\Netravathi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\Sharavathi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\Tunga.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\mfc42.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\MFC42D.DLL"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\mfc70d.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\MFCO42D.DLL"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\MSVCP60.DLL"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\MSVCP60D.DLL"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\MSVCRTD.DLL"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\kannada\ASCII\WINDOWS\KKT v 2.0\output\Text_Converter.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Kuvempu Kannada Thantramsha 1.5 Test"; Filename: "{app}\Kuvempu.exe"
Name: "{group}\{cm:UninstallProgram,Kuvempu Kannada Thantramsha 1.5 Test}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Kuvempu Kannada Thantramsha 1.5 Test"; Filename: "{app}\Kuvempu.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Kuvempu.exe"; Description: "{cm:LaunchProgram,Kuvempu Kannada Thantramsha 1.5 Test}"; Flags: nowait postinstall skipifsilent



